spring.application.name=trackerapi
spring.mongodb.uri=mongodb+srv://srikarchikku95_db_user:QesdtmG4m3SwiBOK@srikar-db.tvwnq3t.mongodb.net/?appName=srikar-db
spring.mongodb.database=srikar-db
spring.data.mongodb.auto-index-creation=true
app.jwt.secret=GreenTrackCarbonTrackingSuperSecretSecretKeyKey2026!
